require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/disease_photos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # DiseasePhoto. As you add validations to DiseasePhoto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DiseasePhoto.create! valid_attributes
      get disease_photos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      disease_photo = DiseasePhoto.create! valid_attributes
      get disease_photo_url(disease_photo)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_disease_photo_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      disease_photo = DiseasePhoto.create! valid_attributes
      get edit_disease_photo_url(disease_photo)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DiseasePhoto" do
        expect {
          post disease_photos_url, params: { disease_photo: valid_attributes }
        }.to change(DiseasePhoto, :count).by(1)
      end

      it "redirects to the created disease_photo" do
        post disease_photos_url, params: { disease_photo: valid_attributes }
        expect(response).to redirect_to(disease_photo_url(DiseasePhoto.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DiseasePhoto" do
        expect {
          post disease_photos_url, params: { disease_photo: invalid_attributes }
        }.to change(DiseasePhoto, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post disease_photos_url, params: { disease_photo: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested disease_photo" do
        disease_photo = DiseasePhoto.create! valid_attributes
        patch disease_photo_url(disease_photo), params: { disease_photo: new_attributes }
        disease_photo.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the disease_photo" do
        disease_photo = DiseasePhoto.create! valid_attributes
        patch disease_photo_url(disease_photo), params: { disease_photo: new_attributes }
        disease_photo.reload
        expect(response).to redirect_to(disease_photo_url(disease_photo))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        disease_photo = DiseasePhoto.create! valid_attributes
        patch disease_photo_url(disease_photo), params: { disease_photo: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested disease_photo" do
      disease_photo = DiseasePhoto.create! valid_attributes
      expect {
        delete disease_photo_url(disease_photo)
      }.to change(DiseasePhoto, :count).by(-1)
    end

    it "redirects to the disease_photos list" do
      disease_photo = DiseasePhoto.create! valid_attributes
      delete disease_photo_url(disease_photo)
      expect(response).to redirect_to(disease_photos_url)
    end
  end
end
