require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/disease_symptoms", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # DiseaseSymptom. As you add validations to DiseaseSymptom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DiseaseSymptom.create! valid_attributes
      get disease_symptoms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      disease_symptom = DiseaseSymptom.create! valid_attributes
      get disease_symptom_url(disease_symptom)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_disease_symptom_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      disease_symptom = DiseaseSymptom.create! valid_attributes
      get edit_disease_symptom_url(disease_symptom)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DiseaseSymptom" do
        expect {
          post disease_symptoms_url, params: { disease_symptom: valid_attributes }
        }.to change(DiseaseSymptom, :count).by(1)
      end

      it "redirects to the created disease_symptom" do
        post disease_symptoms_url, params: { disease_symptom: valid_attributes }
        expect(response).to redirect_to(disease_symptom_url(DiseaseSymptom.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DiseaseSymptom" do
        expect {
          post disease_symptoms_url, params: { disease_symptom: invalid_attributes }
        }.to change(DiseaseSymptom, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post disease_symptoms_url, params: { disease_symptom: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested disease_symptom" do
        disease_symptom = DiseaseSymptom.create! valid_attributes
        patch disease_symptom_url(disease_symptom), params: { disease_symptom: new_attributes }
        disease_symptom.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the disease_symptom" do
        disease_symptom = DiseaseSymptom.create! valid_attributes
        patch disease_symptom_url(disease_symptom), params: { disease_symptom: new_attributes }
        disease_symptom.reload
        expect(response).to redirect_to(disease_symptom_url(disease_symptom))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        disease_symptom = DiseaseSymptom.create! valid_attributes
        patch disease_symptom_url(disease_symptom), params: { disease_symptom: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested disease_symptom" do
      disease_symptom = DiseaseSymptom.create! valid_attributes
      expect {
        delete disease_symptom_url(disease_symptom)
      }.to change(DiseaseSymptom, :count).by(-1)
    end

    it "redirects to the disease_symptoms list" do
      disease_symptom = DiseaseSymptom.create! valid_attributes
      delete disease_symptom_url(disease_symptom)
      expect(response).to redirect_to(disease_symptoms_url)
    end
  end
end
