require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/disease_statuses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # DiseaseStatus. As you add validations to DiseaseStatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DiseaseStatus.create! valid_attributes
      get disease_statuses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      disease_status = DiseaseStatus.create! valid_attributes
      get disease_status_url(disease_status)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_disease_status_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      disease_status = DiseaseStatus.create! valid_attributes
      get edit_disease_status_url(disease_status)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DiseaseStatus" do
        expect {
          post disease_statuses_url, params: { disease_status: valid_attributes }
        }.to change(DiseaseStatus, :count).by(1)
      end

      it "redirects to the created disease_status" do
        post disease_statuses_url, params: { disease_status: valid_attributes }
        expect(response).to redirect_to(disease_status_url(DiseaseStatus.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DiseaseStatus" do
        expect {
          post disease_statuses_url, params: { disease_status: invalid_attributes }
        }.to change(DiseaseStatus, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post disease_statuses_url, params: { disease_status: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested disease_status" do
        disease_status = DiseaseStatus.create! valid_attributes
        patch disease_status_url(disease_status), params: { disease_status: new_attributes }
        disease_status.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the disease_status" do
        disease_status = DiseaseStatus.create! valid_attributes
        patch disease_status_url(disease_status), params: { disease_status: new_attributes }
        disease_status.reload
        expect(response).to redirect_to(disease_status_url(disease_status))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        disease_status = DiseaseStatus.create! valid_attributes
        patch disease_status_url(disease_status), params: { disease_status: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested disease_status" do
      disease_status = DiseaseStatus.create! valid_attributes
      expect {
        delete disease_status_url(disease_status)
      }.to change(DiseaseStatus, :count).by(-1)
    end

    it "redirects to the disease_statuses list" do
      disease_status = DiseaseStatus.create! valid_attributes
      delete disease_status_url(disease_status)
      expect(response).to redirect_to(disease_statuses_url)
    end
  end
end
