require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/measurements", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Measurement. As you add validations to Measurement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Measurement.create! valid_attributes
      get measurements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      measurement = Measurement.create! valid_attributes
      get measurement_url(measurement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_measurement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      measurement = Measurement.create! valid_attributes
      get edit_measurement_url(measurement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Measurement" do
        expect {
          post measurements_url, params: { measurement: valid_attributes }
        }.to change(Measurement, :count).by(1)
      end

      it "redirects to the created measurement" do
        post measurements_url, params: { measurement: valid_attributes }
        expect(response).to redirect_to(measurement_url(Measurement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Measurement" do
        expect {
          post measurements_url, params: { measurement: invalid_attributes }
        }.to change(Measurement, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post measurements_url, params: { measurement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested measurement" do
        measurement = Measurement.create! valid_attributes
        patch measurement_url(measurement), params: { measurement: new_attributes }
        measurement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the measurement" do
        measurement = Measurement.create! valid_attributes
        patch measurement_url(measurement), params: { measurement: new_attributes }
        measurement.reload
        expect(response).to redirect_to(measurement_url(measurement))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        measurement = Measurement.create! valid_attributes
        patch measurement_url(measurement), params: { measurement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested measurement" do
      measurement = Measurement.create! valid_attributes
      expect {
        delete measurement_url(measurement)
      }.to change(Measurement, :count).by(-1)
    end

    it "redirects to the measurements list" do
      measurement = Measurement.create! valid_attributes
      delete measurement_url(measurement)
      expect(response).to redirect_to(measurements_url)
    end
  end
end
