require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/treatment_updates", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TreatmentUpdate. As you add validations to TreatmentUpdate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TreatmentUpdate.create! valid_attributes
      get treatment_updates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      treatment_update = TreatmentUpdate.create! valid_attributes
      get treatment_update_url(treatment_update)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_treatment_update_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      treatment_update = TreatmentUpdate.create! valid_attributes
      get edit_treatment_update_url(treatment_update)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TreatmentUpdate" do
        expect {
          post treatment_updates_url, params: { treatment_update: valid_attributes }
        }.to change(TreatmentUpdate, :count).by(1)
      end

      it "redirects to the created treatment_update" do
        post treatment_updates_url, params: { treatment_update: valid_attributes }
        expect(response).to redirect_to(treatment_update_url(TreatmentUpdate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TreatmentUpdate" do
        expect {
          post treatment_updates_url, params: { treatment_update: invalid_attributes }
        }.to change(TreatmentUpdate, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post treatment_updates_url, params: { treatment_update: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested treatment_update" do
        treatment_update = TreatmentUpdate.create! valid_attributes
        patch treatment_update_url(treatment_update), params: { treatment_update: new_attributes }
        treatment_update.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the treatment_update" do
        treatment_update = TreatmentUpdate.create! valid_attributes
        patch treatment_update_url(treatment_update), params: { treatment_update: new_attributes }
        treatment_update.reload
        expect(response).to redirect_to(treatment_update_url(treatment_update))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        treatment_update = TreatmentUpdate.create! valid_attributes
        patch treatment_update_url(treatment_update), params: { treatment_update: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested treatment_update" do
      treatment_update = TreatmentUpdate.create! valid_attributes
      expect {
        delete treatment_update_url(treatment_update)
      }.to change(TreatmentUpdate, :count).by(-1)
    end

    it "redirects to the treatment_updates list" do
      treatment_update = TreatmentUpdate.create! valid_attributes
      delete treatment_update_url(treatment_update)
      expect(response).to redirect_to(treatment_updates_url)
    end
  end
end
