default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'chronlife_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'chronlife_test') %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'chronlife_production') %>
